tasks:
  - source: tasks.get.metadata
    name: get
    product:
      metadata: products/metadata.csv
      changelog: products/changelog.txt

    
  - source: scripts/clean.py
    name: clean
    product:
      nb: products/output_cleaning.ipynb
      cleaned_metadata: products/cleaned_metadata.parquet
    params:
      sample: True
      link_journal: False
  